<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityManager;

/**
 * EpisodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EpisodeRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Cette fonction retourne les épisodes à venir, par rapport à la date courante.
     * @return array
     */
    public function findNextCalendar()
    {
        $date = new \DateTime();
        $em = $this->getEntityManager();
        $queryBuilder = $em->createQueryBuilder();

        $query = $queryBuilder->select('e')
            ->from('AppBundle:Episode', 'e')
            ->where("e.date > '" . $date->format("Y-m-d") . "'")
            ->getQuery();

        return $query->getResult();
    }

}
