<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * TVShowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TVShowRepository extends EntityRepository
{

    public function getTVShow($first_result, $max_results = 20)
    {
        $qb = $this->createQueryBuilder('t');
        $qb
            ->select('t')
            ->setFirstResult(($first_result) * $max_results)
            ->setMaxResults($max_results);

        $pag = new Paginator($qb);
        return $pag;
    }

    public function search($data)
    {
        $em = $this->getEntityManager();
        $queryBuilder = $em->createQueryBuilder();

        $query = $queryBuilder->select("t")
            ->from("AppBundle:TVShow", 't');

        $query
            ->where("t.name like :name")
            ->orWhere("t.synopsis like :name")
            ->setParameter("name", "%" . $data);

        return $query->getQuery()->getResult();
    }

}
